const:
  default-page-size: 20

file:
  directory: D:/SEA/download/greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey


mybatis:
  configuration:
    map-underscore-to-camel-case: true # snake_case column명을 자동으로 camel_case형으로 변환
  mapper-locations: mappers/**/*.xml

spring:
  application:
  name: GreenGramVer3

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_jpa
    username: root
    password: green502
  jackson:
      default-property-inclusion: non_null # 응답 JSON을 만들 때 null인 속성은 제외한다.

  jpa: # JPA 사용
    database: mysql
    hibernate:
      ddl-auto: create # entity를 서버 기동 때마다 drop 후 create 한다
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true # 로그 찍을 때 보기 편하게 포맷팅
        order_updates: true # JPA Batch 작업 활성화
    show-sql: true # JPA가 만든 쿼리문 로그에 출력

  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true